language: php
sudo: false

cache: vendor

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'hhvm'

before_install:
  - composer config -g repositories.packagist path $(pwd)
  - composer global require 'hirak/prestissimo:@dev'
  - composer config -g --unset repositories.packagist

install:
  - composer install --no-progress --profile

script:
  - composer test

after_success:
  - php bin/ocular.phar code-coverage:upload --format=php-clover artifacts/clover.xml
  - php bin/coveralls.phar -v
