language: php
sudo: false

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

install:
  - composer install --no-progress --profile

script:
  - composer test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover artifacts/clover.xml

matrix:
  allow_failures:
    - php: hhvm
